### PR TITLE
QUICK-FIX: Fix tree view for request

### PR DESCRIPTION
**Pull request by pr1moz**

### CODE REVIEW

**Comment by vladan-m** [comment]
@pr1moz This is really good work. However there are few minor things that we can tweak. Here is the list:
- [ ] Instead of file name `tree_item_request.mustache` please rename it into something more suitable for common use. You can name it `tree_item_common.mustache` for example. So we can use it as a common template for different object types
- [ ] Inside of `tree-request.mustache` and `tree_item_request.mustache` please update copyright informations with correct year and person (in this case you). That way, if someone else needs to know who created this file or made changes in it, it will contact correct person and spare some time
- [ ] All those different types (regulation, objective and issues) have different columns in real app. Find out which one and update your tree view with those info. Audi is different so you will need to create new template for audit types and optimise tree view accordingly.
- [ ] Remove `#QuickWorkflowCreate` element from `tree-request.mustache` file and remove workflow modal from the bottom of that file
- [ ] Inside `tree_item_request.mustache` indentation is little bit off after title.

**Comment by pr1moz** [comment]
@vladan-m I've fixed all the issues, except for the types layout. If each type has a different columns, they can't really be in the same view, so its an issue with the data I assume. The requests page has 4 different types of objects in the same view (issue, audit, system, process). If this is ok, then I need to know which columns are common to all of them. Or am I looking at this completely wrong? :)

**Comment by vladan-m** [comment]
@pr1moz Can you check in task list which ones are done.

**Comment by pr1moz** [comment]
- [x] Instead of file name tree_item_request.mustache please rename it into something more suitable for common use. You can name it tree_item_common.mustache for example. So we can use it as a common template for different object types
- [x] Inside of tree-request.mustache and tree_item_request.mustache please update copyright informations with correct year and person (in this case you). That way, if someone else needs to know who created this file or made changes in it, it will contact correct person and spare some time
- [x] All those different types (regulation, objective and issues) have different columns in real app. Find out which one and update your tree view with those info. Audi is different so you will need to create new template for audit types and optimise tree view accordingly.
- [x] Remove #QuickWorkflowCreate element from tree-request.mustache file and remove workflow modal from the bottom of that file
- [x] Inside tree_item_request.mustache indentation is little bit off after title.
- [x] Fix all linting errors in files that you are working on

**Comment by pr1moz** [comment]
@vladan-m I've pushed fixes for linting errors and hopefully all the fixes for the tree-view :) I'm not sure if the generator is working correctly - I tried using it to generate names, but when I try to display owner.name (since it returns an object) it's empty. So I hardcoded the name, since everything else is.

**Comment by vladan-m** [comment]
@pr1moz Your changes are good. Let's now, remove linting errors from `objectives.js` and `regulations.js` files. Also, In `tree_item_common.mustache` and in `tree_item_request.mustache` find out if you need mustache expressions `if_equals` and remove those that are redundant. Also, it will be required from you to explain which ones are redundant and how you figured it out. :smile:

**Comment by pr1moz** [comment]
@vladan-m I fixed the linting errors and removed two unnecessary ifs (those that had if its a task type) and left an if that checks if it's not a task :)

**Comment by vladan-m** [comment]
@pr1moz Inside `tree_item_request.mustache` you can also remove `{{^if_equals type "assessment"}}` and `{{^if_equals type "control"}}` expressions cause we are gonna use that template just for requests types

**Comment by pr1moz** [comment]
@vladan-m this template is currently being on those two as well:

```
control: '/static/mustache/mockup_base_templates/tree_item_common.mustache',
assessment: '/static/mustache/mockup_base_templates/tree_item_common.mustache',
regulation: '/static/mustache/mockup_base_templates/tree_item_common.mustache',
objective: '/static/mustache/mockup_base_templates/tree_item_common.mustache',
```

Should I remove them in the tree_view.js as well?

**Comment by vladan-m** [comment]
:+1:

**Pull request merged**
