### PR TITLE
Fix mockup script errors

### PR DESCRIPTION
**Pull request by anze3db**
There were collisions with template names and some other issues. I'm not sure if this fixed all the issues, but it should fix most of them.

@vladan-m please click through the mockups. If you see a script error it's probably about a template file not being loaded.

### CODE REVIEW

**Comment by vladan-m** [comment]
@Smotko I see that you removed everything from base_templates but there is no `mockup_base_template` folder with all the files inside your PR.

**Comment by vladan-m** [comment]
@Smotko Should I wait for your fix or should I do changes based on what you did so far?

**Comment by anze3db** [comment]
Sorry, those files should have been renamed. Fixed

**Comment by vladan-m** [comment]
thanks.

**Pull request merged**
